datasource:
  master:
    url: jdbc:mysql://172.16.16.20:5506/demo?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: demo
    password: ENC(Rz+5doDRe9b0XNWEYf0jEq6ALHZJHkVqYLN5WDWB4j/GXbpIr+UR3hJxtATvnOqZT6vtugo+yViiOlUDatW1HA==) #密码加密：druid 密码加密：https://www.cnblogs.com/babycomeon/p/11582303.html dynamic密码加密：https://dynamic-datasource.com/guide/advance/Encode.html
    driver-class-name: com.mysql.jdbc.Driver # 3.2.0开始支持SPI可省略此配置
    p6spy: true # 如果这个库不需要可单独关闭。
  slave_1:
    url: jdbc:mysql://172.16.16.20:5506/demo2?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: demo
    password: ENC(Rz+5doDRe9b0XNWEYf0jEq6ALHZJHkVqYLN5WDWB4j/GXbpIr+UR3hJxtATvnOqZT6vtugo+yViiOlUDatW1HA==)
    driver-class-name: com.mysql.jdbc.Driver

#  privateKey:MIIBVQIBADANBgkqhkiG9w0BAQEFAASCAT8wggE7AgEAAkEAxw6pDKIe62T1pNh/s0BoMjfgv4CmZFq0RoQczmK8e1ddxokQU3uU+7+KkRgpneg9CGiXKJhDUbkdnvmNd/hcWwIDAQABAkAX5Qef75ockar3FdIGd3XKiXCeLFhM9aJsUJGQqMONXpI6Ke1QKQpNS2uqApUAUjRORPhopeF9bZK7YqZs9rXpAiEA5xpDP28SwD1RkYy0qzjKjN7qZb0G7HrDZMigSkP70OUCIQDcgJkB/mXzz0MmbivhfEdJpH0phm/qRduFdNfrD+TkPwIgeWc2hJBZDVwpCYkdMAV5gl9oS2HtzTUAiGVMrzbfhnECIQC/hSbg93DgOoatq4WLnWFh0nAwECfGyRRpr1oXPj/mCwIhAJc43vu80xPz7+m2NaC5wahVtsOvWoXesEnaEgb2niLr
#  publicKey:MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAMcOqQyiHutk9aTYf7NAaDI34L+ApmRatEaEHM5ivHtXXcaJEFN7lPu/ipEYKZ3oPQholyiYQ1G5HZ75jXf4XFsCAwEAAQ==
#  password:Rz+5doDRe9b0XNWEYf0jEq6ALHZJHkVqYLN5WDWB4j/GXbpIr+UR3hJxtATvnOqZT6vtugo+yViiOlUDatW1HA==
#  原始密码：123456